topics:
  reference_trajectory: /planning/trajectory_generator/neural_network_based_planner/diffusion_planner_node/debug/mppi/reference_trajectory
  odometry: /localization/kinematic_state"
  acceleration: /localization/acceleration
  steering: /vehicle/status/steering_status
  tracked_objects: /perception/object_recognition/tracking/objects
  lanelet_map: /map/vector_map
  route: /planning/route

thresholds:
  required_stale_ms: 100.0
  optional_stale_ms: 250.0
